package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.CoursePackage;
import cn.com.itcast.sport.entry.CoursePackageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CoursePackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int countByExample(CoursePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int deleteByExample(CoursePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int insert(CoursePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int insertSelective(CoursePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    List<CoursePackage> selectByExample(CoursePackageExample example);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    CoursePackage selectByPrimaryKey(Integer id);

    List<CoursePackage> queryNearPackages(@Param("userCode") String userCode);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") CoursePackage record, @Param("example") CoursePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int updateByExample(@Param("record") CoursePackage record, @Param("example") CoursePackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int updateByPrimaryKeySelective(CoursePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_package
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    int updateByPrimaryKey(CoursePackage record);
}