package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.CourseType;
import cn.com.itcast.sport.entry.CourseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int countByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int deleteByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int insert(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int insertSelective(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    List<CourseType> selectByExampleWithBLOBs(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    List<CourseType> selectByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    CourseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") CourseType record, @Param("example") CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") CourseType record, @Param("example") CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int updateByExample(@Param("record") CourseType record, @Param("example") CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int updateByPrimaryKeySelective(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    int updateByPrimaryKey(CourseType record);
}