package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.LeaveMain;
import cn.com.itcast.sport.entry.LeaveMainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeaveMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int countByExample(LeaveMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int deleteByExample(LeaveMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int insert(LeaveMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int insertSelective(LeaveMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    List<LeaveMain> selectByExampleWithBLOBs(LeaveMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    List<LeaveMain> selectByExample(LeaveMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    LeaveMain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") LeaveMain record, @Param("example") LeaveMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") LeaveMain record, @Param("example") LeaveMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int updateByExample(@Param("record") LeaveMain record, @Param("example") LeaveMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int updateByPrimaryKeySelective(LeaveMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(LeaveMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    int updateByPrimaryKey(LeaveMain record);
}