package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.OrderCourse;
import cn.com.itcast.sport.entry.OrderCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int countByExample(OrderCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int deleteByExample(OrderCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int insert(OrderCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int insertSelective(OrderCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    List<OrderCourse> selectByExample(OrderCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    OrderCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderCourse record, @Param("example") OrderCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int updateByExample(@Param("record") OrderCourse record, @Param("example") OrderCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int updateByPrimaryKeySelective(OrderCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_course
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    int updateByPrimaryKey(OrderCourse record);
}