package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.PackageUser;
import cn.com.itcast.sport.entry.PackageUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PackageUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int countByExample(PackageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int deleteByExample(PackageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int insert(PackageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int insertSelective(PackageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    List<PackageUser> selectByExample(PackageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    PackageUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") PackageUser record, @Param("example") PackageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int updateByExample(@Param("record") PackageUser record, @Param("example") PackageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int updateByPrimaryKeySelective(PackageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_user
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    int updateByPrimaryKey(PackageUser record);
}