package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.SalaryMonth;
import cn.com.itcast.sport.entry.SalaryMonthExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SalaryMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int countByExample(SalaryMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int deleteByExample(SalaryMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int insert(SalaryMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int insertSelective(SalaryMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    List<SalaryMonth> selectByExampleWithBLOBs(SalaryMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    List<SalaryMonth> selectByExample(SalaryMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    SalaryMonth selectByPrimaryKey(Integer id);

    List<SalaryMonth> querySpendingBytime(String monthTime);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") SalaryMonth record, @Param("example") SalaryMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") SalaryMonth record, @Param("example") SalaryMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int updateByExample(@Param("record") SalaryMonth record, @Param("example") SalaryMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int updateByPrimaryKeySelective(SalaryMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SalaryMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_month
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    int updateByPrimaryKey(SalaryMonth record);
}