package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.ShopCart;
import cn.com.itcast.sport.entry.ShopCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int countByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int deleteByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int insert(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int insertSelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    List<ShopCart> selectByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    ShopCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int updateByExample(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int updateByPrimaryKeySelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_cart
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    int updateByPrimaryKey(ShopCart record);
}