package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.ShopOrder;
import cn.com.itcast.sport.entry.ShopOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ShopOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int countByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int deleteByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int insert(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int insertSelective(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    List<ShopOrder> selectByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    ShopOrder selectByPrimaryKey(Integer id);

    List<ShopOrder> queryIncomeBytime(@Param("monthTime") String monthTime);

    List<Map<String,Object>> queryConsumption(@Param("userName")  String userName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") ShopOrder record, @Param("example") ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int updateByExample(@Param("record") ShopOrder record, @Param("example") ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int updateByPrimaryKeySelective(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    int updateByPrimaryKey(ShopOrder record);
}