package cn.com.itcast.sport.dao;

import cn.com.itcast.sport.entry.SiteMsg;
import cn.com.itcast.sport.entry.SiteMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int countByExample(SiteMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int deleteByExample(SiteMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int insert(SiteMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int insertSelective(SiteMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    List<SiteMsg> selectByExampleWithBLOBs(SiteMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    List<SiteMsg> selectByExample(SiteMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    SiteMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") SiteMsg record, @Param("example") SiteMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") SiteMsg record, @Param("example") SiteMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int updateByExample(@Param("record") SiteMsg record, @Param("example") SiteMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int updateByPrimaryKeySelective(SiteMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SiteMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_msg
     *
     * @mbggenerated Sat Apr 04 15:11:11 CST 2020
     */
    int updateByPrimaryKey(SiteMsg record);
}