package cn.com.itcast.sport.entry;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class CoursePackage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.id
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.package_code
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    private String packageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.package_num
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    private String packageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.package_name
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.time_long
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    private String timeLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.start_time
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.end_time
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.status
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.is_deleted
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_package.course_code
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    private String courseCode;

    private String isPutCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.id
     *
     * @return the value of course_package.id
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.id
     *
     * @param id the value for course_package.id
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.package_code
     *
     * @return the value of course_package.package_code
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public String getPackageCode() {
        return packageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.package_code
     *
     * @param packageCode the value for course_package.package_code
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setPackageCode(String packageCode) {
        this.packageCode = packageCode == null ? null : packageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.package_num
     *
     * @return the value of course_package.package_num
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public String getPackageNum() {
        return packageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.package_num
     *
     * @param packageNum the value for course_package.package_num
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setPackageNum(String packageNum) {
        this.packageNum = packageNum == null ? null : packageNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.package_name
     *
     * @return the value of course_package.package_name
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.package_name
     *
     * @param packageName the value for course_package.package_name
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.time_long
     *
     * @return the value of course_package.time_long
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public String getTimeLong() {
        return timeLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.time_long
     *
     * @param timeLong the value for course_package.time_long
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setTimeLong(String timeLong) {
        this.timeLong = timeLong == null ? null : timeLong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.start_time
     *
     * @return the value of course_package.start_time
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.start_time
     *
     * @param startTime the value for course_package.start_time
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.end_time
     *
     * @return the value of course_package.end_time
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.end_time
     *
     * @param endTime the value for course_package.end_time
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.status
     *
     * @return the value of course_package.status
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.status
     *
     * @param status the value for course_package.status
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.is_deleted
     *
     * @return the value of course_package.is_deleted
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.is_deleted
     *
     * @param isDeleted the value for course_package.is_deleted
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_package.course_code
     *
     * @return the value of course_package.course_code
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public String getCourseCode() {
        return courseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_package.course_code
     *
     * @param courseCode the value for course_package.course_code
     *
     * @mbggenerated Sun Apr 05 14:47:45 CST 2020
     */
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode == null ? null : courseCode.trim();
    }

    public String getIsPutCard() {
        return isPutCard;
    }

    public void setIsPutCard(String isPutCard) {
        this.isPutCard = isPutCard;
    }
}