package cn.com.itcast.sport.entry;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourseMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public CourseMainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNull() {
            addCriterion("course_name is null");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNotNull() {
            addCriterion("course_name is not null");
            return (Criteria) this;
        }

        public Criteria andCourseNameEqualTo(String value) {
            addCriterion("course_name =", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotEqualTo(String value) {
            addCriterion("course_name <>", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThan(String value) {
            addCriterion("course_name >", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThanOrEqualTo(String value) {
            addCriterion("course_name >=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThan(String value) {
            addCriterion("course_name <", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThanOrEqualTo(String value) {
            addCriterion("course_name <=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLike(String value) {
            addCriterion("course_name like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotLike(String value) {
            addCriterion("course_name not like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameIn(List<String> values) {
            addCriterion("course_name in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotIn(List<String> values) {
            addCriterion("course_name not in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameBetween(String value1, String value2) {
            addCriterion("course_name between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotBetween(String value1, String value2) {
            addCriterion("course_name not between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseCodeIsNull() {
            addCriterion("course_code is null");
            return (Criteria) this;
        }

        public Criteria andCourseCodeIsNotNull() {
            addCriterion("course_code is not null");
            return (Criteria) this;
        }

        public Criteria andCourseCodeEqualTo(String value) {
            addCriterion("course_code =", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeNotEqualTo(String value) {
            addCriterion("course_code <>", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeGreaterThan(String value) {
            addCriterion("course_code >", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeGreaterThanOrEqualTo(String value) {
            addCriterion("course_code >=", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeLessThan(String value) {
            addCriterion("course_code <", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeLessThanOrEqualTo(String value) {
            addCriterion("course_code <=", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeLike(String value) {
            addCriterion("course_code like", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeNotLike(String value) {
            addCriterion("course_code not like", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeIn(List<String> values) {
            addCriterion("course_code in", values, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeNotIn(List<String> values) {
            addCriterion("course_code not in", values, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeBetween(String value1, String value2) {
            addCriterion("course_code between", value1, value2, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeNotBetween(String value1, String value2) {
            addCriterion("course_code not between", value1, value2, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCoursePicIsNull() {
            addCriterion("course_pic is null");
            return (Criteria) this;
        }

        public Criteria andCoursePicIsNotNull() {
            addCriterion("course_pic is not null");
            return (Criteria) this;
        }

        public Criteria andCoursePicEqualTo(String value) {
            addCriterion("course_pic =", value, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicNotEqualTo(String value) {
            addCriterion("course_pic <>", value, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicGreaterThan(String value) {
            addCriterion("course_pic >", value, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicGreaterThanOrEqualTo(String value) {
            addCriterion("course_pic >=", value, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicLessThan(String value) {
            addCriterion("course_pic <", value, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicLessThanOrEqualTo(String value) {
            addCriterion("course_pic <=", value, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicLike(String value) {
            addCriterion("course_pic like", value, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicNotLike(String value) {
            addCriterion("course_pic not like", value, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicIn(List<String> values) {
            addCriterion("course_pic in", values, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicNotIn(List<String> values) {
            addCriterion("course_pic not in", values, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicBetween(String value1, String value2) {
            addCriterion("course_pic between", value1, value2, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCoursePicNotBetween(String value1, String value2) {
            addCriterion("course_pic not between", value1, value2, "coursePic");
            return (Criteria) this;
        }

        public Criteria andCourseVideoIsNull() {
            addCriterion("course_video is null");
            return (Criteria) this;
        }

        public Criteria andCourseVideoIsNotNull() {
            addCriterion("course_video is not null");
            return (Criteria) this;
        }

        public Criteria andCourseVideoEqualTo(String value) {
            addCriterion("course_video =", value, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoNotEqualTo(String value) {
            addCriterion("course_video <>", value, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoGreaterThan(String value) {
            addCriterion("course_video >", value, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoGreaterThanOrEqualTo(String value) {
            addCriterion("course_video >=", value, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoLessThan(String value) {
            addCriterion("course_video <", value, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoLessThanOrEqualTo(String value) {
            addCriterion("course_video <=", value, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoLike(String value) {
            addCriterion("course_video like", value, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoNotLike(String value) {
            addCriterion("course_video not like", value, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoIn(List<String> values) {
            addCriterion("course_video in", values, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoNotIn(List<String> values) {
            addCriterion("course_video not in", values, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoBetween(String value1, String value2) {
            addCriterion("course_video between", value1, value2, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCourseVideoNotBetween(String value1, String value2) {
            addCriterion("course_video not between", value1, value2, "courseVideo");
            return (Criteria) this;
        }

        public Criteria andCoursePriceIsNull() {
            addCriterion("course_price is null");
            return (Criteria) this;
        }

        public Criteria andCoursePriceIsNotNull() {
            addCriterion("course_price is not null");
            return (Criteria) this;
        }

        public Criteria andCoursePriceEqualTo(BigDecimal value) {
            addCriterion("course_price =", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceNotEqualTo(BigDecimal value) {
            addCriterion("course_price <>", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceGreaterThan(BigDecimal value) {
            addCriterion("course_price >", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("course_price >=", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceLessThan(BigDecimal value) {
            addCriterion("course_price <", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("course_price <=", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceIn(List<BigDecimal> values) {
            addCriterion("course_price in", values, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceNotIn(List<BigDecimal> values) {
            addCriterion("course_price not in", values, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("course_price between", value1, value2, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("course_price not between", value1, value2, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedIsNull() {
            addCriterion("is_recommended is null");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedIsNotNull() {
            addCriterion("is_recommended is not null");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedEqualTo(String value) {
            addCriterion("is_recommended =", value, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedNotEqualTo(String value) {
            addCriterion("is_recommended <>", value, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedGreaterThan(String value) {
            addCriterion("is_recommended >", value, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedGreaterThanOrEqualTo(String value) {
            addCriterion("is_recommended >=", value, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedLessThan(String value) {
            addCriterion("is_recommended <", value, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedLessThanOrEqualTo(String value) {
            addCriterion("is_recommended <=", value, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedLike(String value) {
            addCriterion("is_recommended like", value, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedNotLike(String value) {
            addCriterion("is_recommended not like", value, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedIn(List<String> values) {
            addCriterion("is_recommended in", values, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedNotIn(List<String> values) {
            addCriterion("is_recommended not in", values, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedBetween(String value1, String value2) {
            addCriterion("is_recommended between", value1, value2, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andIsRecommendedNotBetween(String value1, String value2) {
            addCriterion("is_recommended not between", value1, value2, "isRecommended");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameIsNull() {
            addCriterion("couese_type_name is null");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameIsNotNull() {
            addCriterion("couese_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameEqualTo(String value) {
            addCriterion("couese_type_name =", value, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameNotEqualTo(String value) {
            addCriterion("couese_type_name <>", value, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameGreaterThan(String value) {
            addCriterion("couese_type_name >", value, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("couese_type_name >=", value, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameLessThan(String value) {
            addCriterion("couese_type_name <", value, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameLessThanOrEqualTo(String value) {
            addCriterion("couese_type_name <=", value, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameLike(String value) {
            addCriterion("couese_type_name like", value, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameNotLike(String value) {
            addCriterion("couese_type_name not like", value, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameIn(List<String> values) {
            addCriterion("couese_type_name in", values, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameNotIn(List<String> values) {
            addCriterion("couese_type_name not in", values, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameBetween(String value1, String value2) {
            addCriterion("couese_type_name between", value1, value2, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCoueseTypeNameNotBetween(String value1, String value2) {
            addCriterion("couese_type_name not between", value1, value2, "coueseTypeName");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeIsNull() {
            addCriterion("course_type_code is null");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeIsNotNull() {
            addCriterion("course_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeEqualTo(String value) {
            addCriterion("course_type_code =", value, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeNotEqualTo(String value) {
            addCriterion("course_type_code <>", value, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeGreaterThan(String value) {
            addCriterion("course_type_code >", value, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("course_type_code >=", value, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeLessThan(String value) {
            addCriterion("course_type_code <", value, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("course_type_code <=", value, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeLike(String value) {
            addCriterion("course_type_code like", value, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeNotLike(String value) {
            addCriterion("course_type_code not like", value, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeIn(List<String> values) {
            addCriterion("course_type_code in", values, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeNotIn(List<String> values) {
            addCriterion("course_type_code not in", values, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeBetween(String value1, String value2) {
            addCriterion("course_type_code between", value1, value2, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andCourseTypeCodeNotBetween(String value1, String value2) {
            addCriterion("course_type_code not between", value1, value2, "courseTypeCode");
            return (Criteria) this;
        }

        public Criteria andClickNumIsNull() {
            addCriterion("click_num is null");
            return (Criteria) this;
        }

        public Criteria andClickNumIsNotNull() {
            addCriterion("click_num is not null");
            return (Criteria) this;
        }

        public Criteria andClickNumEqualTo(Integer value) {
            addCriterion("click_num =", value, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumNotEqualTo(Integer value) {
            addCriterion("click_num <>", value, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumGreaterThan(Integer value) {
            addCriterion("click_num >", value, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("click_num >=", value, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumLessThan(Integer value) {
            addCriterion("click_num <", value, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumLessThanOrEqualTo(Integer value) {
            addCriterion("click_num <=", value, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumIn(List<Integer> values) {
            addCriterion("click_num in", values, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumNotIn(List<Integer> values) {
            addCriterion("click_num not in", values, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumBetween(Integer value1, Integer value2) {
            addCriterion("click_num between", value1, value2, "clickNum");
            return (Criteria) this;
        }

        public Criteria andClickNumNotBetween(Integer value1, Integer value2) {
            addCriterion("click_num not between", value1, value2, "clickNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumIsNull() {
            addCriterion("buy_num is null");
            return (Criteria) this;
        }

        public Criteria andBuyNumIsNotNull() {
            addCriterion("buy_num is not null");
            return (Criteria) this;
        }

        public Criteria andBuyNumEqualTo(Integer value) {
            addCriterion("buy_num =", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotEqualTo(Integer value) {
            addCriterion("buy_num <>", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumGreaterThan(Integer value) {
            addCriterion("buy_num >", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_num >=", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumLessThan(Integer value) {
            addCriterion("buy_num <", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumLessThanOrEqualTo(Integer value) {
            addCriterion("buy_num <=", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumIn(List<Integer> values) {
            addCriterion("buy_num in", values, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotIn(List<Integer> values) {
            addCriterion("buy_num not in", values, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumBetween(Integer value1, Integer value2) {
            addCriterion("buy_num between", value1, value2, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_num not between", value1, value2, "buyNum");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("user_code is null");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("user_code is not null");
            return (Criteria) this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("user_code =", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("user_code <>", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("user_code >", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("user_code >=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("user_code <", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("user_code <=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("user_code like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("user_code not like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeIn(List<String> values) {
            addCriterion("user_code in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotIn(List<String> values) {
            addCriterion("user_code not in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("user_code between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("user_code not between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndIsNull() {
            addCriterion("is_apply_end is null");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndIsNotNull() {
            addCriterion("is_apply_end is not null");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndEqualTo(String value) {
            addCriterion("is_apply_end =", value, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndNotEqualTo(String value) {
            addCriterion("is_apply_end <>", value, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndGreaterThan(String value) {
            addCriterion("is_apply_end >", value, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndGreaterThanOrEqualTo(String value) {
            addCriterion("is_apply_end >=", value, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndLessThan(String value) {
            addCriterion("is_apply_end <", value, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndLessThanOrEqualTo(String value) {
            addCriterion("is_apply_end <=", value, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndLike(String value) {
            addCriterion("is_apply_end like", value, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndNotLike(String value) {
            addCriterion("is_apply_end not like", value, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndIn(List<String> values) {
            addCriterion("is_apply_end in", values, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndNotIn(List<String> values) {
            addCriterion("is_apply_end not in", values, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndBetween(String value1, String value2) {
            addCriterion("is_apply_end between", value1, value2, "isApplyEnd");
            return (Criteria) this;
        }

        public Criteria andIsApplyEndNotBetween(String value1, String value2) {
            addCriterion("is_apply_end not between", value1, value2, "isApplyEnd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_main
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 07 23:35:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_main
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}