package cn.com.itcast.sport.entry;

import java.util.Date;

public class CourseType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_type.id
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_type.type_code
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_type.type_name
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_type.create_time
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_type.is_deleted
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_type.comment
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_type.id
     *
     * @return the value of course_type.id
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_type.id
     *
     * @param id the value for course_type.id
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_type.type_code
     *
     * @return the value of course_type.type_code
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_type.type_code
     *
     * @param typeCode the value for course_type.type_code
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_type.type_name
     *
     * @return the value of course_type.type_name
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_type.type_name
     *
     * @param typeName the value for course_type.type_name
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_type.create_time
     *
     * @return the value of course_type.create_time
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_type.create_time
     *
     * @param createTime the value for course_type.create_time
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_type.is_deleted
     *
     * @return the value of course_type.is_deleted
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_type.is_deleted
     *
     * @param isDeleted the value for course_type.is_deleted
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_type.comment
     *
     * @return the value of course_type.comment
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_type.comment
     *
     * @param comment the value for course_type.comment
     *
     * @mbggenerated Tue Mar 24 22:35:38 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}