package cn.com.itcast.sport.entry;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

public class CourseMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.id
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.course_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.course_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String courseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.course_pic
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String coursePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.course_video
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String courseVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.course_price
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private BigDecimal coursePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.start_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.end_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.status
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.is_recommended
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String isRecommended;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.couese_type_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String coueseTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.course_type_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String courseTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.click_num
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private Integer clickNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.buy_num
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private Integer buyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.is_deleted
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.create_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.user_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.user_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.is_apply_end
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String isApplyEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_main.course_desc
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    private String courseDesc;

    private String isHas;
    private String teachPic;
    private List<HashMap<String,String>> courseCommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.id
     *
     * @return the value of course_main.id
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.id
     *
     * @param id the value for course_main.id
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.course_name
     *
     * @return the value of course_main.course_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.course_name
     *
     * @param courseName the value for course_main.course_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.course_code
     *
     * @return the value of course_main.course_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getCourseCode() {
        return courseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.course_code
     *
     * @param courseCode the value for course_main.course_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode == null ? null : courseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.course_pic
     *
     * @return the value of course_main.course_pic
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getCoursePic() {
        return coursePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.course_pic
     *
     * @param coursePic the value for course_main.course_pic
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCoursePic(String coursePic) {
        this.coursePic = coursePic == null ? null : coursePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.course_video
     *
     * @return the value of course_main.course_video
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getCourseVideo() {
        return courseVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.course_video
     *
     * @param courseVideo the value for course_main.course_video
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCourseVideo(String courseVideo) {
        this.courseVideo = courseVideo == null ? null : courseVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.course_price
     *
     * @return the value of course_main.course_price
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public BigDecimal getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.course_price
     *
     * @param coursePrice the value for course_main.course_price
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCoursePrice(BigDecimal coursePrice) {
        this.coursePrice = coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.start_time
     *
     * @return the value of course_main.start_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.start_time
     *
     * @param startTime the value for course_main.start_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.end_time
     *
     * @return the value of course_main.end_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.end_time
     *
     * @param endTime the value for course_main.end_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.status
     *
     * @return the value of course_main.status
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.status
     *
     * @param status the value for course_main.status
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.is_recommended
     *
     * @return the value of course_main.is_recommended
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getIsRecommended() {
        return isRecommended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.is_recommended
     *
     * @param isRecommended the value for course_main.is_recommended
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setIsRecommended(String isRecommended) {
        this.isRecommended = isRecommended == null ? null : isRecommended.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.couese_type_name
     *
     * @return the value of course_main.couese_type_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getCoueseTypeName() {
        return coueseTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.couese_type_name
     *
     * @param coueseTypeName the value for course_main.couese_type_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCoueseTypeName(String coueseTypeName) {
        this.coueseTypeName = coueseTypeName == null ? null : coueseTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.course_type_code
     *
     * @return the value of course_main.course_type_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getCourseTypeCode() {
        return courseTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.course_type_code
     *
     * @param courseTypeCode the value for course_main.course_type_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCourseTypeCode(String courseTypeCode) {
        this.courseTypeCode = courseTypeCode == null ? null : courseTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.click_num
     *
     * @return the value of course_main.click_num
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.click_num
     *
     * @param clickNum the value for course_main.click_num
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.buy_num
     *
     * @return the value of course_main.buy_num
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public Integer getBuyNum() {
        return buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.buy_num
     *
     * @param buyNum the value for course_main.buy_num
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setBuyNum(Integer buyNum) {
        this.buyNum = buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.is_deleted
     *
     * @return the value of course_main.is_deleted
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.is_deleted
     *
     * @param isDeleted the value for course_main.is_deleted
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.create_time
     *
     * @return the value of course_main.create_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.create_time
     *
     * @param createTime the value for course_main.create_time
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.user_code
     *
     * @return the value of course_main.user_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.user_code
     *
     * @param userCode the value for course_main.user_code
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.user_name
     *
     * @return the value of course_main.user_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.user_name
     *
     * @param userName the value for course_main.user_name
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.is_apply_end
     *
     * @return the value of course_main.is_apply_end
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getIsApplyEnd() {
        return isApplyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.is_apply_end
     *
     * @param isApplyEnd the value for course_main.is_apply_end
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setIsApplyEnd(String isApplyEnd) {
        this.isApplyEnd = isApplyEnd == null ? null : isApplyEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_main.course_desc
     *
     * @return the value of course_main.course_desc
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public String getCourseDesc() {
        return courseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_main.course_desc
     *
     * @param courseDesc the value for course_main.course_desc
     *
     * @mbggenerated Tue Apr 07 23:35:38 CST 2020
     */
    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc == null ? null : courseDesc.trim();
    }

    public String getIsHas() {
        return isHas;
    }

    public void setIsHas(String isHas) {
        this.isHas = isHas;
    }

    public String getTeachPic() {
        return teachPic;
    }

    public void setTeachPic(String teachPic) {
        this.teachPic = teachPic;
    }

    public List<HashMap<String, String>> getCourseCommend() {
        return courseCommend;
    }

    public void setCourseCommend(List<HashMap<String, String>> courseCommend) {
        this.courseCommend = courseCommend;
    }
}