package cn.com.itcast.sport.entry;

import java.util.Date;

public class LeaveMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.id
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.course_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String courseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.course_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.package_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.package_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String packageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.package_before_start_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private Date packageBeforeStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.package_before_end_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private Date packageBeforeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.package_adjust_start_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private Date packageAdjustStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.package_adjust_end_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private Date packageAdjustEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.start_user_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String startUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.start_user_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String startUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.check_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.status
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.is_deleted
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_main.check_comment
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    private String checkComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.id
     *
     * @return the value of leave_main.id
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.id
     *
     * @param id the value for leave_main.id
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.course_code
     *
     * @return the value of leave_main.course_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getCourseCode() {
        return courseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.course_code
     *
     * @param courseCode the value for leave_main.course_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode == null ? null : courseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.course_name
     *
     * @return the value of leave_main.course_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.course_name
     *
     * @param courseName the value for leave_main.course_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.package_name
     *
     * @return the value of leave_main.package_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.package_name
     *
     * @param packageName the value for leave_main.package_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.package_code
     *
     * @return the value of leave_main.package_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getPackageCode() {
        return packageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.package_code
     *
     * @param packageCode the value for leave_main.package_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setPackageCode(String packageCode) {
        this.packageCode = packageCode == null ? null : packageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.package_before_start_time
     *
     * @return the value of leave_main.package_before_start_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public Date getPackageBeforeStartTime() {
        return packageBeforeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.package_before_start_time
     *
     * @param packageBeforeStartTime the value for leave_main.package_before_start_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setPackageBeforeStartTime(Date packageBeforeStartTime) {
        this.packageBeforeStartTime = packageBeforeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.package_before_end_time
     *
     * @return the value of leave_main.package_before_end_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public Date getPackageBeforeEndTime() {
        return packageBeforeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.package_before_end_time
     *
     * @param packageBeforeEndTime the value for leave_main.package_before_end_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setPackageBeforeEndTime(Date packageBeforeEndTime) {
        this.packageBeforeEndTime = packageBeforeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.package_adjust_start_time
     *
     * @return the value of leave_main.package_adjust_start_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public Date getPackageAdjustStartTime() {
        return packageAdjustStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.package_adjust_start_time
     *
     * @param packageAdjustStartTime the value for leave_main.package_adjust_start_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setPackageAdjustStartTime(Date packageAdjustStartTime) {
        this.packageAdjustStartTime = packageAdjustStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.package_adjust_end_time
     *
     * @return the value of leave_main.package_adjust_end_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public Date getPackageAdjustEndTime() {
        return packageAdjustEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.package_adjust_end_time
     *
     * @param packageAdjustEndTime the value for leave_main.package_adjust_end_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setPackageAdjustEndTime(Date packageAdjustEndTime) {
        this.packageAdjustEndTime = packageAdjustEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.start_user_name
     *
     * @return the value of leave_main.start_user_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getStartUserName() {
        return startUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.start_user_name
     *
     * @param startUserName the value for leave_main.start_user_name
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setStartUserName(String startUserName) {
        this.startUserName = startUserName == null ? null : startUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.start_user_code
     *
     * @return the value of leave_main.start_user_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getStartUserCode() {
        return startUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.start_user_code
     *
     * @param startUserCode the value for leave_main.start_user_code
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setStartUserCode(String startUserCode) {
        this.startUserCode = startUserCode == null ? null : startUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.check_time
     *
     * @return the value of leave_main.check_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.check_time
     *
     * @param checkTime the value for leave_main.check_time
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.status
     *
     * @return the value of leave_main.status
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.status
     *
     * @param status the value for leave_main.status
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.is_deleted
     *
     * @return the value of leave_main.is_deleted
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.is_deleted
     *
     * @param isDeleted the value for leave_main.is_deleted
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_main.check_comment
     *
     * @return the value of leave_main.check_comment
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getCheckComment() {
        return checkComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_main.check_comment
     *
     * @param checkComment the value for leave_main.check_comment
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setCheckComment(String checkComment) {
        this.checkComment = checkComment == null ? null : checkComment.trim();
    }
}