package cn.com.itcast.sport.entry;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LeaveMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public LeaveMainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCourseCodeIsNull() {
            addCriterion("course_code is null");
            return (Criteria) this;
        }

        public Criteria andCourseCodeIsNotNull() {
            addCriterion("course_code is not null");
            return (Criteria) this;
        }

        public Criteria andCourseCodeEqualTo(String value) {
            addCriterion("course_code =", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeNotEqualTo(String value) {
            addCriterion("course_code <>", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeGreaterThan(String value) {
            addCriterion("course_code >", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeGreaterThanOrEqualTo(String value) {
            addCriterion("course_code >=", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeLessThan(String value) {
            addCriterion("course_code <", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeLessThanOrEqualTo(String value) {
            addCriterion("course_code <=", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeLike(String value) {
            addCriterion("course_code like", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeNotLike(String value) {
            addCriterion("course_code not like", value, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeIn(List<String> values) {
            addCriterion("course_code in", values, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeNotIn(List<String> values) {
            addCriterion("course_code not in", values, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeBetween(String value1, String value2) {
            addCriterion("course_code between", value1, value2, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseCodeNotBetween(String value1, String value2) {
            addCriterion("course_code not between", value1, value2, "courseCode");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNull() {
            addCriterion("course_name is null");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNotNull() {
            addCriterion("course_name is not null");
            return (Criteria) this;
        }

        public Criteria andCourseNameEqualTo(String value) {
            addCriterion("course_name =", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotEqualTo(String value) {
            addCriterion("course_name <>", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThan(String value) {
            addCriterion("course_name >", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThanOrEqualTo(String value) {
            addCriterion("course_name >=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThan(String value) {
            addCriterion("course_name <", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThanOrEqualTo(String value) {
            addCriterion("course_name <=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLike(String value) {
            addCriterion("course_name like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotLike(String value) {
            addCriterion("course_name not like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameIn(List<String> values) {
            addCriterion("course_name in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotIn(List<String> values) {
            addCriterion("course_name not in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameBetween(String value1, String value2) {
            addCriterion("course_name between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotBetween(String value1, String value2) {
            addCriterion("course_name not between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNull() {
            addCriterion("package_name is null");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNotNull() {
            addCriterion("package_name is not null");
            return (Criteria) this;
        }

        public Criteria andPackageNameEqualTo(String value) {
            addCriterion("package_name =", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotEqualTo(String value) {
            addCriterion("package_name <>", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThan(String value) {
            addCriterion("package_name >", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
            addCriterion("package_name >=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThan(String value) {
            addCriterion("package_name <", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThanOrEqualTo(String value) {
            addCriterion("package_name <=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLike(String value) {
            addCriterion("package_name like", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotLike(String value) {
            addCriterion("package_name not like", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameIn(List<String> values) {
            addCriterion("package_name in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotIn(List<String> values) {
            addCriterion("package_name not in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameBetween(String value1, String value2) {
            addCriterion("package_name between", value1, value2, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotBetween(String value1, String value2) {
            addCriterion("package_name not between", value1, value2, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageCodeIsNull() {
            addCriterion("package_code is null");
            return (Criteria) this;
        }

        public Criteria andPackageCodeIsNotNull() {
            addCriterion("package_code is not null");
            return (Criteria) this;
        }

        public Criteria andPackageCodeEqualTo(String value) {
            addCriterion("package_code =", value, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeNotEqualTo(String value) {
            addCriterion("package_code <>", value, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeGreaterThan(String value) {
            addCriterion("package_code >", value, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeGreaterThanOrEqualTo(String value) {
            addCriterion("package_code >=", value, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeLessThan(String value) {
            addCriterion("package_code <", value, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeLessThanOrEqualTo(String value) {
            addCriterion("package_code <=", value, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeLike(String value) {
            addCriterion("package_code like", value, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeNotLike(String value) {
            addCriterion("package_code not like", value, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeIn(List<String> values) {
            addCriterion("package_code in", values, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeNotIn(List<String> values) {
            addCriterion("package_code not in", values, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeBetween(String value1, String value2) {
            addCriterion("package_code between", value1, value2, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageCodeNotBetween(String value1, String value2) {
            addCriterion("package_code not between", value1, value2, "packageCode");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeIsNull() {
            addCriterion("package_before_start_time is null");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeIsNotNull() {
            addCriterion("package_before_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeEqualTo(Date value) {
            addCriterion("package_before_start_time =", value, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeNotEqualTo(Date value) {
            addCriterion("package_before_start_time <>", value, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeGreaterThan(Date value) {
            addCriterion("package_before_start_time >", value, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("package_before_start_time >=", value, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeLessThan(Date value) {
            addCriterion("package_before_start_time <", value, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("package_before_start_time <=", value, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeIn(List<Date> values) {
            addCriterion("package_before_start_time in", values, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeNotIn(List<Date> values) {
            addCriterion("package_before_start_time not in", values, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeBetween(Date value1, Date value2) {
            addCriterion("package_before_start_time between", value1, value2, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("package_before_start_time not between", value1, value2, "packageBeforeStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeIsNull() {
            addCriterion("package_before_end_time is null");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeIsNotNull() {
            addCriterion("package_before_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeEqualTo(Date value) {
            addCriterion("package_before_end_time =", value, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeNotEqualTo(Date value) {
            addCriterion("package_before_end_time <>", value, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeGreaterThan(Date value) {
            addCriterion("package_before_end_time >", value, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("package_before_end_time >=", value, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeLessThan(Date value) {
            addCriterion("package_before_end_time <", value, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("package_before_end_time <=", value, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeIn(List<Date> values) {
            addCriterion("package_before_end_time in", values, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeNotIn(List<Date> values) {
            addCriterion("package_before_end_time not in", values, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeBetween(Date value1, Date value2) {
            addCriterion("package_before_end_time between", value1, value2, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageBeforeEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("package_before_end_time not between", value1, value2, "packageBeforeEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeIsNull() {
            addCriterion("package_adjust_start_time is null");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeIsNotNull() {
            addCriterion("package_adjust_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeEqualTo(Date value) {
            addCriterion("package_adjust_start_time =", value, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeNotEqualTo(Date value) {
            addCriterion("package_adjust_start_time <>", value, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeGreaterThan(Date value) {
            addCriterion("package_adjust_start_time >", value, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("package_adjust_start_time >=", value, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeLessThan(Date value) {
            addCriterion("package_adjust_start_time <", value, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("package_adjust_start_time <=", value, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeIn(List<Date> values) {
            addCriterion("package_adjust_start_time in", values, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeNotIn(List<Date> values) {
            addCriterion("package_adjust_start_time not in", values, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeBetween(Date value1, Date value2) {
            addCriterion("package_adjust_start_time between", value1, value2, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("package_adjust_start_time not between", value1, value2, "packageAdjustStartTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeIsNull() {
            addCriterion("package_adjust_end_time is null");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeIsNotNull() {
            addCriterion("package_adjust_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeEqualTo(Date value) {
            addCriterion("package_adjust_end_time =", value, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeNotEqualTo(Date value) {
            addCriterion("package_adjust_end_time <>", value, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeGreaterThan(Date value) {
            addCriterion("package_adjust_end_time >", value, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("package_adjust_end_time >=", value, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeLessThan(Date value) {
            addCriterion("package_adjust_end_time <", value, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("package_adjust_end_time <=", value, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeIn(List<Date> values) {
            addCriterion("package_adjust_end_time in", values, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeNotIn(List<Date> values) {
            addCriterion("package_adjust_end_time not in", values, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeBetween(Date value1, Date value2) {
            addCriterion("package_adjust_end_time between", value1, value2, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andPackageAdjustEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("package_adjust_end_time not between", value1, value2, "packageAdjustEndTime");
            return (Criteria) this;
        }

        public Criteria andStartUserNameIsNull() {
            addCriterion("start_user_name is null");
            return (Criteria) this;
        }

        public Criteria andStartUserNameIsNotNull() {
            addCriterion("start_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andStartUserNameEqualTo(String value) {
            addCriterion("start_user_name =", value, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameNotEqualTo(String value) {
            addCriterion("start_user_name <>", value, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameGreaterThan(String value) {
            addCriterion("start_user_name >", value, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("start_user_name >=", value, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameLessThan(String value) {
            addCriterion("start_user_name <", value, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameLessThanOrEqualTo(String value) {
            addCriterion("start_user_name <=", value, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameLike(String value) {
            addCriterion("start_user_name like", value, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameNotLike(String value) {
            addCriterion("start_user_name not like", value, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameIn(List<String> values) {
            addCriterion("start_user_name in", values, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameNotIn(List<String> values) {
            addCriterion("start_user_name not in", values, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameBetween(String value1, String value2) {
            addCriterion("start_user_name between", value1, value2, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserNameNotBetween(String value1, String value2) {
            addCriterion("start_user_name not between", value1, value2, "startUserName");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeIsNull() {
            addCriterion("start_user_code is null");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeIsNotNull() {
            addCriterion("start_user_code is not null");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeEqualTo(String value) {
            addCriterion("start_user_code =", value, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeNotEqualTo(String value) {
            addCriterion("start_user_code <>", value, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeGreaterThan(String value) {
            addCriterion("start_user_code >", value, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("start_user_code >=", value, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeLessThan(String value) {
            addCriterion("start_user_code <", value, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeLessThanOrEqualTo(String value) {
            addCriterion("start_user_code <=", value, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeLike(String value) {
            addCriterion("start_user_code like", value, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeNotLike(String value) {
            addCriterion("start_user_code not like", value, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeIn(List<String> values) {
            addCriterion("start_user_code in", values, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeNotIn(List<String> values) {
            addCriterion("start_user_code not in", values, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeBetween(String value1, String value2) {
            addCriterion("start_user_code between", value1, value2, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andStartUserCodeNotBetween(String value1, String value2) {
            addCriterion("start_user_code not between", value1, value2, "startUserCode");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIsNull() {
            addCriterion("check_time is null");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIsNotNull() {
            addCriterion("check_time is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTimeEqualTo(Date value) {
            addCriterion("check_time =", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotEqualTo(Date value) {
            addCriterion("check_time <>", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeGreaterThan(Date value) {
            addCriterion("check_time >", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("check_time >=", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeLessThan(Date value) {
            addCriterion("check_time <", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeLessThanOrEqualTo(Date value) {
            addCriterion("check_time <=", value, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeIn(List<Date> values) {
            addCriterion("check_time in", values, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotIn(List<Date> values) {
            addCriterion("check_time not in", values, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeBetween(Date value1, Date value2) {
            addCriterion("check_time between", value1, value2, "checkTime");
            return (Criteria) this;
        }

        public Criteria andCheckTimeNotBetween(Date value1, Date value2) {
            addCriterion("check_time not between", value1, value2, "checkTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table leave_main
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 09 21:42:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table leave_main
     *
     * @mbggenerated Thu Apr 09 21:42:00 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}