package cn.com.itcast.sport.entry;

import java.math.BigDecimal;
import java.util.Date;

public class OrderCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.id
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.user_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.order_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.course_name
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.course_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private String courseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.course_price
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private BigDecimal coursePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.course_pic
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private String coursePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.create_time
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.course_comment
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private String courseComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.status
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_course.is_deleted
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.id
     *
     * @return the value of order_course.id
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.id
     *
     * @param id the value for order_course.id
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.user_code
     *
     * @return the value of order_course.user_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.user_code
     *
     * @param userCode the value for order_course.user_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.order_code
     *
     * @return the value of order_course.order_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.order_code
     *
     * @param orderCode the value for order_course.order_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.course_name
     *
     * @return the value of order_course.course_name
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.course_name
     *
     * @param courseName the value for order_course.course_name
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.course_code
     *
     * @return the value of order_course.course_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public String getCourseCode() {
        return courseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.course_code
     *
     * @param courseCode the value for order_course.course_code
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode == null ? null : courseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.course_price
     *
     * @return the value of order_course.course_price
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public BigDecimal getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.course_price
     *
     * @param coursePrice the value for order_course.course_price
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setCoursePrice(BigDecimal coursePrice) {
        this.coursePrice = coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.course_pic
     *
     * @return the value of order_course.course_pic
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public String getCoursePic() {
        return coursePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.course_pic
     *
     * @param coursePic the value for order_course.course_pic
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setCoursePic(String coursePic) {
        this.coursePic = coursePic == null ? null : coursePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.create_time
     *
     * @return the value of order_course.create_time
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.create_time
     *
     * @param createTime the value for order_course.create_time
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.course_comment
     *
     * @return the value of order_course.course_comment
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public String getCourseComment() {
        return courseComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.course_comment
     *
     * @param courseComment the value for order_course.course_comment
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setCourseComment(String courseComment) {
        this.courseComment = courseComment == null ? null : courseComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.status
     *
     * @return the value of order_course.status
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.status
     *
     * @param status the value for order_course.status
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_course.is_deleted
     *
     * @return the value of order_course.is_deleted
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_course.is_deleted
     *
     * @param isDeleted the value for order_course.is_deleted
     *
     * @mbggenerated Sun Apr 05 17:30:13 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}