package cn.com.itcast.sport.entry;

import java.util.Date;

public class PackageUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_user.id
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_user.user_code
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_user.real_start_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    private Date realStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_user.real_end_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    private Date realEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_user.is_sign_in
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    private String isSignIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_user.sign_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    private Date signTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_user.is_deleted
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_user.package_code
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    private String packageCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_user.id
     *
     * @return the value of package_user.id
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_user.id
     *
     * @param id the value for package_user.id
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_user.user_code
     *
     * @return the value of package_user.user_code
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_user.user_code
     *
     * @param userCode the value for package_user.user_code
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_user.real_start_time
     *
     * @return the value of package_user.real_start_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public Date getRealStartTime() {
        return realStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_user.real_start_time
     *
     * @param realStartTime the value for package_user.real_start_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public void setRealStartTime(Date realStartTime) {
        this.realStartTime = realStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_user.real_end_time
     *
     * @return the value of package_user.real_end_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public Date getRealEndTime() {
        return realEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_user.real_end_time
     *
     * @param realEndTime the value for package_user.real_end_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public void setRealEndTime(Date realEndTime) {
        this.realEndTime = realEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_user.is_sign_in
     *
     * @return the value of package_user.is_sign_in
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public String getIsSignIn() {
        return isSignIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_user.is_sign_in
     *
     * @param isSignIn the value for package_user.is_sign_in
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public void setIsSignIn(String isSignIn) {
        this.isSignIn = isSignIn == null ? null : isSignIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_user.sign_time
     *
     * @return the value of package_user.sign_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_user.sign_time
     *
     * @param signTime the value for package_user.sign_time
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_user.is_deleted
     *
     * @return the value of package_user.is_deleted
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_user.is_deleted
     *
     * @param isDeleted the value for package_user.is_deleted
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_user.package_code
     *
     * @return the value of package_user.package_code
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public String getPackageCode() {
        return packageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_user.package_code
     *
     * @param packageCode the value for package_user.package_code
     *
     * @mbggenerated Sun Apr 05 15:21:35 CST 2020
     */
    public void setPackageCode(String packageCode) {
        this.packageCode = packageCode == null ? null : packageCode.trim();
    }
}