package cn.com.itcast.sport.entry;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class SalaryMonth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.id
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.name
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.user_code
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.basic_money
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private BigDecimal basicMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.commission
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private BigDecimal commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.leave_deduct
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private BigDecimal leaveDeduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.real_money
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private BigDecimal realMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.create_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.is_deleted
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.salary_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */

    private Date salaryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.send_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_month.comment
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.id
     *
     * @return the value of salary_month.id
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.id
     *
     * @param id the value for salary_month.id
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.name
     *
     * @return the value of salary_month.name
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.name
     *
     * @param name the value for salary_month.name
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.user_code
     *
     * @return the value of salary_month.user_code
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.user_code
     *
     * @param userCode the value for salary_month.user_code
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.basic_money
     *
     * @return the value of salary_month.basic_money
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public BigDecimal getBasicMoney() {
        return basicMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.basic_money
     *
     * @param basicMoney the value for salary_month.basic_money
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setBasicMoney(BigDecimal basicMoney) {
        this.basicMoney = basicMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.commission
     *
     * @return the value of salary_month.commission
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.commission
     *
     * @param commission the value for salary_month.commission
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.leave_deduct
     *
     * @return the value of salary_month.leave_deduct
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public BigDecimal getLeaveDeduct() {
        return leaveDeduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.leave_deduct
     *
     * @param leaveDeduct the value for salary_month.leave_deduct
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setLeaveDeduct(BigDecimal leaveDeduct) {
        this.leaveDeduct = leaveDeduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.real_money
     *
     * @return the value of salary_month.real_money
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public BigDecimal getRealMoney() {
        return realMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.real_money
     *
     * @param realMoney the value for salary_month.real_money
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setRealMoney(BigDecimal realMoney) {
        this.realMoney = realMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.create_time
     *
     * @return the value of salary_month.create_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.create_time
     *
     * @param createTime the value for salary_month.create_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.is_deleted
     *
     * @return the value of salary_month.is_deleted
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.is_deleted
     *
     * @param isDeleted the value for salary_month.is_deleted
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.salary_time
     *
     * @return the value of salary_month.salary_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM")
    @JsonFormat(pattern = "yyyy-MM", timezone = "GMT+8")
    public Date getSalaryTime() {
        return salaryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.salary_time
     *
     * @param salaryTime the value for salary_month.salary_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setSalaryTime(Date salaryTime) {
        this.salaryTime = salaryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.send_time
     *
     * @return the value of salary_month.send_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.send_time
     *
     * @param sendTime the value for salary_month.send_time
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_month.comment
     *
     * @return the value of salary_month.comment
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_month.comment
     *
     * @param comment the value for salary_month.comment
     *
     * @mbggenerated Sun Mar 29 11:34:15 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}