package cn.com.itcast.sport.entry;

import java.math.BigDecimal;
import java.util.Date;

public class ShopOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.id
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.user_code
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.order_code
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.status
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.pay_price
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    private BigDecimal payPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.create_time
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.pay_time
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.is_deleted
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.id
     *
     * @return the value of shop_order.id
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.id
     *
     * @param id the value for shop_order.id
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.user_code
     *
     * @return the value of shop_order.user_code
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.user_code
     *
     * @param userCode the value for shop_order.user_code
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_code
     *
     * @return the value of shop_order.order_code
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_code
     *
     * @param orderCode the value for shop_order.order_code
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.status
     *
     * @return the value of shop_order.status
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.status
     *
     * @param status the value for shop_order.status
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.pay_price
     *
     * @return the value of shop_order.pay_price
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public BigDecimal getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.pay_price
     *
     * @param payPrice the value for shop_order.pay_price
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public void setPayPrice(BigDecimal payPrice) {
        this.payPrice = payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.create_time
     *
     * @return the value of shop_order.create_time
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.create_time
     *
     * @param createTime the value for shop_order.create_time
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.pay_time
     *
     * @return the value of shop_order.pay_time
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.pay_time
     *
     * @param payTime the value for shop_order.pay_time
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.is_deleted
     *
     * @return the value of shop_order.is_deleted
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.is_deleted
     *
     * @param isDeleted the value for shop_order.is_deleted
     *
     * @mbggenerated Sat Apr 04 21:01:14 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}