package cn.com.itcast.sport.entry;

import java.math.BigDecimal;
import java.util.Date;

public class ShopCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.id
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.user_code
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.course_name
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.course_code
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private String courseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.is_deleted
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.create_time
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.update_time
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.course_pic
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private String coursePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.course_price
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    private BigDecimal coursePrice;

    private String courseDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.id
     *
     * @return the value of shop_cart.id
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.id
     *
     * @param id the value for shop_cart.id
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.user_code
     *
     * @return the value of shop_cart.user_code
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.user_code
     *
     * @param userCode the value for shop_cart.user_code
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.course_name
     *
     * @return the value of shop_cart.course_name
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.course_name
     *
     * @param courseName the value for shop_cart.course_name
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.course_code
     *
     * @return the value of shop_cart.course_code
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public String getCourseCode() {
        return courseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.course_code
     *
     * @param courseCode the value for shop_cart.course_code
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode == null ? null : courseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.is_deleted
     *
     * @return the value of shop_cart.is_deleted
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.is_deleted
     *
     * @param isDeleted the value for shop_cart.is_deleted
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.create_time
     *
     * @return the value of shop_cart.create_time
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.create_time
     *
     * @param createTime the value for shop_cart.create_time
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.update_time
     *
     * @return the value of shop_cart.update_time
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.update_time
     *
     * @param updateTime the value for shop_cart.update_time
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.course_pic
     *
     * @return the value of shop_cart.course_pic
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public String getCoursePic() {
        return coursePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.course_pic
     *
     * @param coursePic the value for shop_cart.course_pic
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setCoursePic(String coursePic) {
        this.coursePic = coursePic == null ? null : coursePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.course_price
     *
     * @return the value of shop_cart.course_price
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public BigDecimal getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.course_price
     *
     * @param coursePrice the value for shop_cart.course_price
     *
     * @mbggenerated Sun Apr 05 16:53:11 CST 2020
     */
    public void setCoursePrice(BigDecimal coursePrice) {
        this.coursePrice = coursePrice;
    }

    public String getCourseDesc() {
        return courseDesc;
    }

    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc;
    }
}